### ISSUE TITLE
FIXME: lectura desde el gestor

### ISSUE THREAD

**Issue by marialuciacastillog** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#11]
No se están leyendo correctamente los archivos desde el Python. Es decir, no está funcionando correctamente la función leer_archivo del gestor.

**Comment by anadan10102006** [comment]
FIXED: UNA VEZ CAMBIADA LA LOGICA PARA USAR DATAFRAMES, SE SOLUCIONO 

    def leer_archivo(ruta, palabra_clave, columna_unica):
        try:
            df = pd.read_excel(ruta, header=None)

            # Limpiar filas completamente vacías
            df.dropna(how='all', inplace=True)

            # Buscar la fila del encabezado correcto
            fila_encabezado = None
            for idx, fila in df.iterrows():
                if "PROGRAMA ACADÉMICO" in fila.values:  # Buscar la columna clave
                    fila_encabezado = idx
                    break

            if fila_encabezado is None:
                raise KeyError("No se encontró la columna 'PROGRAMA ACADÉMICO' en el archivo.")

            # Releer el archivo usando la fila del encabezado detectado
            df = pd.read_excel(ruta, header=fila_encabezado)

            # Estandarizar nombres de columnas
            df.columns = df.columns.str.strip().str.upper()

            # Validar si la columna clave está presente
            if "PROGRAMA ACADÉMICO" not in df.columns:
                raise KeyError("La columna 'PROGRAMA ACADÉMICO' no existe en el archivo después de procesarlo.")

            # Filtrar por palabra clave
            df_palabra_clave = df[df["PROGRAMA ACADÉMICO"].str.contains(palabra_clave, case=False, na=False)]

            # Definir columnas a consolidar según `unico_dato`
            columnas_a_buscar = [
                "CÓDIGO SNIES DEL PROGRAMA", "SEMESTRE"
            ] if columna_unica else [
                "CÓDIGO SNIES DEL PROGRAMA",
                "METODOLOGÍA",
                "PROGRAMA ACADÉMICO",
                "INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)",
                "PRINCIPAL O SECCIONAL",
                "DEPARTAMENTO DE OFERTA DEL PROGRAMA",
                "MUNICIPIO DE OFERTA DEL PROGRAMA",
                "NIVEL DE FORMACIÓN",
                "SEMESTRE"
            ]

            # Selección y consolidación de datos
            ultima_columna = df.columns[-1]
            ultima_columna_df = df_palabra_clave[ultima_columna]
            buscado = df_palabra_clave[columnas_a_buscar]


            buscado = pd.concat([buscado, ultima_columna_df], axis=1)
            resultado = buscado.groupby(columnas_a_buscar).sum(numeric_only=True).reset_index()

            return resultado
