### ISSUE TITLE
FIXME: Filtrado Streamlit

### ISSUE THREAD

**Issue by marialuciacastillog** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#12]
Si bien el filtrado del gestor ya está funcionando correctamente, falta enlazarlo para funcione bien en la interfaz gráfica.

**Comment by anadan10102006** [comment]
FIXED: SE BUSCA EL ANIO Y LOS DATOS POR EL NOMBRE DE LAS COLUMNAS ADECUADO AL TIPO DE ARCHIVOS QUE GENERA NUESTRO PROGRAMA

years_selected = st.multiselect("Selecciona los años para analizar", anios_disponibles)
                    metric_options = ["ADMITIDOS", "GRADUADOS", "INSCRITOS", "MATRICULADOS", "PRIMER CURSO"]
                    metric_selected = st.selectbox("Selecciona el tipo de dato a graficar", metric_options)
                    chart_type = st.radio("Selecciona el tipo de gráfico", ["Barras", "Líneas de tendencia"])

                    if not years_selected:
                        st.error("Selecciona al menos un año para continuar.")
                    else:
                        filtered_columns = [
                            col for col in df.columns if
                            any(col.startswith(f"{metric_selected}_{year}") for year in years_selected)
                        ]
