### ISSUE TITLE
FIXME: Generar las gráficas 

### ISSUE THREAD

**Issue by marialuciacastillog** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#13]
Generar los gráficos de barras y las líneas de tendencia en el archivo de streamlitSNIES.

**Comment by julianagonz** [comment]
Resuelto!! se generan ambos gráficos éxitosamente:
`if chart_type == "Barras":
    grouped_data = graph_data.groupby("Year")["Value"].sum()
    ax.bar(grouped_data.index, grouped_data.values, color='skyblue')
    ax.set_title(f"Comparativa de {metric_selected} entre los años seleccionados")
    ax.set_xlabel("Año")
    ax.set_ylabel(metric_selected)
`

`elif chart_type == "Líneas de tendencia":
    graph_data = graph_data.sort_values("Year")
    ax.plot(
        graph_data["Year"],
        graph_data["Value"],
        marker='o',
        linestyle='-',
        color='b',
        label=f"Tendencia de {metric_selected}"
    )
    ax.set_title(f"Tendencia de {metric_selected} entre los años seleccionados")
    ax.set_xlabel("Año")
    ax.set_ylabel(metric_selected)
    ax.legend(title="Datos")
`
