### ISSUE TITLE
FIXME: Cambiar View

### ISSUE THREAD

**Issue by marialuciacastillog** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#15]
Se deben poder ingresar los datos desde el streamlit y no desde el código fuente!

**Comment by anadan10102006** [comment]
FIXED: MENU IMPLEMENTADO EN STREAMLIT

st.title("¡Bienvenido al **_SNIES Extractor_**! 🎈")
st.write("_Siga las instrucciones a continuación para realizar el análisis y exportación de datos._")

st.subheader("Parametrización Inicial")
st.write("Asegúrese de que la carpeta SNIES_EXTRACTOR esté correctamente configurada con los archivos necesarios.")

if st.button("Confirmar parametrización"):
    st.success("Parametrización confirmada. Puedes continuar con el análisis.")

st.subheader("Selección de parámetros")
anio1 = st.text_input("Escriba el primer año de búsqueda:", value="2020")
anio2 = st.text_input("Escriba el segundo año de búsqueda:", value="2021")

view = View()

valid_anio1, anio1_int = view.validar_entrada_anio(anio1)
valid_anio2, anio2_int = view.validar_entrada_anio(anio2)

if not (valid_anio1 and valid_anio2):
    st.error("Ambos años deben ser valores enteros válidos.")
else:
    palabra_clave = st.text_input("Ingrese una palabra clave para filtrar los datos:", value="")

    if not palabra_clave.strip():
        st.error("Debe ingresar una palabra clave válida.")
    else:
        formato = st.selectbox("Seleccione el formato de archivo para exportar los datos:", ["XLSX", "CSV", "JSON"])

        if st.button("Procesar y Exportar"):
            view.procesar_datos(anio1_int, anio2_int, palabra_clave, formato)

st.subheader("Cierre del programa")
if st.button("Salir"):
    st.success("Recuerde revisar la carpeta de outputs para los archivos exportados. ¡Programa cerrado con éxito!")
