### ISSUE TITLE
FIXME: No recibe CSV

### ISSUE THREAD

**Issue by marialuciacastillog** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#17]
La aplicación ya recibe correctamente los xlsx. Sin embargo, cuando le intento ingresar .csv está generando errores.

**Comment by anadan10102006** [comment]
FIXED: SE IMPLEMENTA LOGICA PARA ABRIR Y BUSCAR DATOS EN CSV

        try:
            if file_extension == "csv":
                df = pd.read_csv(uploaded_file, delimiter=";").dropna()
