### ISSUE TITLE
FIXME: Columnas incorrectas

### ISSUE THREAD

**Issue by marialuciacastillog** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#19]
Anteriormente se filtraba a partir de unas columnas que tenían el año, sin embargo, esta lógica ya no aplica para esta aplicación. Por lo que, se debe arreglar esa forma de filtrar.

**Comment by julianagonz** [comment]
FIXED: Se arregla la lógica que permite seleccionar por año. Ya no se busca en cuanto a columnas, sino que se busca el año reflejado: EJ: "MATRICULADOS_20XX" --> Se extrae el año correspondiente para el análisis
