### ISSUE TITLE
FIXME: CONSOLIDADOS

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#2]
Consolidados no se guardan correctamente;

`@staticmethod
        def buscar_datos_codigos_snies(codigos_snies, rutas_archivos, datos_consolidar):
            """
            Busca datos específicos de TITULOS_SEGUNDO_ARCHIVO en varios archivos y retorna una lista consolidada.

            Args:
                codigos_snies (List[int]): Lista de códigos SNIES a buscar.
                rutas_archivos (List[str]): Rutas de los archivos XLSX donde buscar.
                titulos_segundo (List[str]): Títulos de las columnas de interés.

            Returns:
                List[List]: Lista de filas donde la primera columna es el código SNIES
                            y las demás columnas son los datos buscados.
            """
            datos_consolidados = []

            for ruta in rutas_archivos:
                try:
                    wb = openpyxl.load_workbook(ruta)
                    sheet = wb.active

                    # Identificar las posiciones de las columnas de interés
                    encabezados = None
                    for row in sheet.iter_rows(min_row=1, values_only=True):
                        if "CÓDIGO SNIES DEL PROGRAMA" in row:
                            encabezados = row
                            break

                    if not encabezados:
                        raise ValueError(f"No se encontraron encabezados en el archivo: {ruta}")

                    # Identificar las posiciones de las columnas de interés
                    pos_codigo_snies = encabezados.index("CÓDIGO SNIES DEL PROGRAMA")
                    posiciones_interes = [encabezados.index(titulo) for titulo in datos_consolidar if
                                          titulo in encabezados]

                    if not posiciones_interes:
                        raise ValueError(f"No se encontraron columnas de interés en el archivo: {ruta}")

                    # Leer las filas y buscar los códigos SNIES
                    for row in sheet.iter_rows(min_row=sheet.min_row + 1, values_only=True):
                        if row[pos_codigo_snies] in codigos_snies:
                            fila = [row[pos_codigo_snies]] + [row[pos] for pos in posiciones_interes]
                            datos_consolidados.append(fila)

                except Exception as e:
                    print(f"Error procesando el archivo {ruta}: {e}")

            return datos_consolidados`

**Comment by anadan10102006** [comment]
FIXED: CAMBIO DE LOGICA PARA TRABAJAR CON DATAFRAMES Y DEJAR LA CLASE CONSOLIDADO Y PROGRAMA ACADEMICO, SIMPLIFICANDO LA LOGICA Y SOLUCIONANDO EL PROBLEMA DE CONSOLIDAR   
   
    def procesar_datos(self, anio1, anio2, palabra_clave):
        try:

            anio11 = int(anio1)
            anio22 = int(anio2)

            anios = [anio for anio in range(min(anio11, anio22), max(anio11, anio22) + 1)]
            primero = True
            gestor = GestorXlsx()

            for anio in anios:
                DIRECCIONES = [
                    Settings.ADMITIDOS_FILE_PATH,
                    Settings.GRADUADOS_FILE_PATH,
                    Settings.INSCRITOS_FILE_PATH,
                    Settings.MATRICULADOS_FILE_PATH,
                    Settings.MATRICULADOS_PRIMER_CURSO_FILE_PATH
                ]

                for direccion in DIRECCIONES:
                    ruta_archivo = f"{direccion}{anio}.xlsx"
                    dataframe_minimizado = gestor.leer_archivo(ruta_archivo, palabra_clave, not primero)

                    dataframe_minimizado["CÓDIGO SNIES DEL PROGRAMA"] = dataframe_minimizado["CÓDIGO SNIES DEL PROGRAMA"].astype(str)
                    dataframe_minimizado["SEMESTRE"] = dataframe_minimizado["SEMESTRE"].astype(str)

                    if primero:

                        dataframe_minimizado.rename(columns={"ADMITIDOS": f'{"ADMITIDOS"}_{anio}'}, inplace=True)
                        self.df = dataframe_minimizado
                        primero = False

                    else:
                        for col in dataframe_minimizado.columns:
                            if not (col == "CÓDIGO SNIES DEL PROGRAMA" or col == "SEMESTRE"):
                                dataframe_minimizado.rename(columns={col: f'{col}_{anio}'}, inplace=True)

                        self.df = pd.merge(
                            self.df, dataframe_minimizado,
                            on=["CÓDIGO SNIES DEL PROGRAMA", "SEMESTRE"],
                            how="left"
                        )

        except FileNotFoundError:
            raise FileNotFoundError("Archivo necesario no está cargado al SNIES")
        except Exception as e:
            raise Exception(f"Error al procesar los datos: {e}")

        return self.df
