### ISSUE TITLE
FIXME: Direcciones de los archivo

### ISSUE THREAD

**Issue by marialuciacastillog** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#21]
Ajustar las direcciones de los archivos en Settings.

**Comment by anadan10102006** [comment]
SEMI-FIXED: AL EJECUTAR EN CADA COMPUTADOR SE DEBEN CAMBIAR LAS DIRECCIONES EN EL ARCHIVO SETTINGS Y EN EL ARCHIVO SNIESCONTROLLERSTREAMLIT.
