### ISSUE TITLE
FIXME: función crear_archivos 

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#3]
función `def crear_archivos`:

modificar la función para que permita crear archivos a partir de data frames.

**Comment by marialuciacastillog** [comment]
Ya arreglado!


class Gestor:

    def crear_archivo(self, ruta: str, dataframe: pd.DataFrame) -> bool:

        raise NotImplementedError
        
        
        
class GestorCsv(Gestor):

    def crear_archivo(self, ruta: str, dataframe: pd.DataFrame) -> bool:
        """
        Crea un archivo CSV basado en un DataFrame.

        :param ruta: Ruta donde se guardará el archivo CSV.
        :param dataframe: DataFrame que contiene los datos a guardar.
        :return: True si se crea el archivo correctamente.
        """
        try:
            dataframe.to_csv(ruta, index=False, encoding='utf-8')  # Guarda el DataFrame directamente como CSV
            return True
        except Exception as e:
            print(f"Error al crear el archivo CSV: {e}")
            return False




class GestorJson(Gestor):

    def crear_archivo(self, ruta: str, dataframe: pd.DataFrame) -> bool:
        """
        Crea un archivo JSON basado en un DataFrame.

        :param ruta: Ruta donde se guardará el archivo JSON.
        :param dataframe: DataFrame que contiene los datos a guardar.
        :return: True si se crea el archivo correctamente.
        """
        try:
            dataframe.to_json(ruta, orient='records', indent=4, force_ascii=False)  # Guarda el DataFrame como JSON
            return True
        except Exception as e:
            print(f"Error al crear el archivo JSON: {e}")
            return False




class GestorXlsx(Gestor):
        def crear_archivo(self, ruta: str, dataframe: pd.DataFrame) -> bool:
            """
            Crea un archivo Excel basado en un DataFrame.

            :param ruta: Ruta donde se guardará el archivo Excel.
            :param dataframe: DataFrame que contiene los datos a guardar.
            :return: True si se crea el archivo correctamente.
            """
            try:
                dataframe.to_excel(ruta, index=False, engine='openpyxl')  # Guarda el DataFrame como Excel
                return True
            except Exception as e:
                print(f"Error al crear el archivo Excel: {e}")
                return False

**Comment by marialuciacastillog** [comment]
Ya arreglado!


class Gestor:

    def crear_archivo(self, ruta: str, dataframe: pd.DataFrame) -> bool:

        raise NotImplementedError
        
        
        
class GestorCsv(Gestor):

    def crear_archivo(self, ruta: str, dataframe: pd.DataFrame) -> bool:
        """
        Crea un archivo CSV basado en un DataFrame.

        :param ruta: Ruta donde se guardará el archivo CSV.
        :param dataframe: DataFrame que contiene los datos a guardar.
        :return: True si se crea el archivo correctamente.
        """
        try:
            dataframe.to_csv(ruta, index=False, encoding='utf-8')  # Guarda el DataFrame directamente como CSV
            return True
        except Exception as e:
            print(f"Error al crear el archivo CSV: {e}")
            return False




class GestorJson(Gestor):

    def crear_archivo(self, ruta: str, dataframe: pd.DataFrame) -> bool:
        """
        Crea un archivo JSON basado en un DataFrame.

        :param ruta: Ruta donde se guardará el archivo JSON.
        :param dataframe: DataFrame que contiene los datos a guardar.
        :return: True si se crea el archivo correctamente.
        """
        try:
            dataframe.to_json(ruta, orient='records', indent=4, force_ascii=False)  # Guarda el DataFrame como JSON
            return True
        except Exception as e:
            print(f"Error al crear el archivo JSON: {e}")
            return False




class GestorXlsx(Gestor):
        def crear_archivo(self, ruta: str, dataframe: pd.DataFrame) -> bool:
            """
            Crea un archivo Excel basado en un DataFrame.

            :param ruta: Ruta donde se guardará el archivo Excel.
            :param dataframe: DataFrame que contiene los datos a guardar.
            :return: True si se crea el archivo correctamente.
            """
            try:
                dataframe.to_excel(ruta, index=False, engine='openpyxl')  # Guarda el DataFrame como Excel
                return True
            except Exception as e:
                print(f"Error al crear el archivo Excel: {e}")
                return False
