### ISSUE TITLE
AGREGAR: StreamlitSNIES

### ISSUE THREAD

**Issue by julianagonz** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#4]
STREAMLIT ya recibe y lee archivos desde la máquina. Falta hacer selección de los archivos que el usuario desea analizar.

**Comment by anadan10102006** [comment]
SEMI-FIXED: EL USUARIO PUEDE ANADIR DOCUMENTOS DONDE SE ANALIZAN LOS ARCHIVOS O DOCUMENTOS PERO DEBE HACERLO DIRECTAMENTE EN LA CARPETA, NO DESDE LA INTERFAZ. SIN EMBARGO, PUEDE ANADIR ARCHIVOS CON LOS DATOS YA ESPERADOS EN LA INTERFAZ PARA GENERAR LAS GRAFICAS
