### ISSUE TITLE
FIXME: MANEJAR BUSQUEDA DE PROGRAMAS DESDE STREAMLIT

### ISSUE THREAD

**Issue by anadan10102006** [300CIS017-Object-Oriented-Programming/proyecto-3-yabastapoorfavor#7]
def buscar_programas(self, flag, palabra_clave, id_comparacion):
        lista_programas = []

        try:
            # Filtrar programas por palabra clave y nivel de formación
            for programa in self.programas_academicos.values():
                nombre = programa.programa_academico
                id_nivel = programa.id_nivel_formacion

                if palabra_clave in nombre and id_nivel == id_comparacion:
                    lista_programas.append(programa)
                    print(f"{programa.codigo_snies};{programa.programa_academico};"
                          f"{programa.codigo_de_la_institucion};{programa.institucion_ies};"
                          f"{programa.metodologia}")

            # Generar archivo si flag es True
            if flag:
                opcion = int(input("Desea generar un archivo CSV (1), XLSX (2) o JSON (3): "))
                if opcion not in [1, 2, 3]:
                    raise ValueError("Opción no válida. Debe ser 1, 2 o 3.")

                if opcion == 1:
                    gestor = GestorCsv()
                elif opcion == 2:
                    gestor = GestorXlsx()
                else:
                    gestor = GestorJson()

                gestor.crear_archivo_buscados(self.ruta_output, lista_programas, self.etiquetas_columnas)

        except ValueError as e:
            print(f"Error: {e}")
        except MemoryError as e:
            print(f"Error de memoria: {e}")
        except Exception as e:
            print(f"Se produjo un error: {e}")
        except:
            print("Se produjo un error desconocido.")

**Comment by julianagonz** [comment]
CLOSED: Streamlit maneja el filtrado correctamente
